#!/usr/bin/env bash





                  #########################################################################################################
                  #                                          Zeroday-Fetch                                                #
                  #                                                                                                       #
                  #                                                                                                       #                   
                  #                                                                                                       #
                  #                                                                                                       #
                  #         Author: The 0Day o_O                                                                          #
                  #         Twitter: Fuck Big Tech                                                                        #
                  #         Github: The-0Day                                                                              #
                  #         Gitlab:  The-0Day                                                                             # 
                  #         Instagram: I Don't Use That Shit                                                              #
                  #         Facebook: I Don't Want My Data To Be Available On DarkWeb Lol                                 #
                  #         Email: Zeroday_0day@protonmail.com                                                            #
                  #                                                                                                       #
                  #               License: BSD License 3.0                                                                #
                  #                                                                                                       #
                  #                                                                                                       #
                  #                                                                                                       #
                  #                                                                                                       #
                  #                                                                                                       #
                  #########################################################################################################





BLACK=`tput setaf 0`
RED=`tput setaf 1`
GREEN=`tput setaf 2`
YELLOW=`tput setaf 3`
BLUE=`tput setaf 4`
PURPLE=`tput setaf 5`
CYAN=`tput setaf 6`
WHITE=`tput setaf 7`
BLACK=`tput setaf 8`
ORANGE=`tput setaf 9`
BOLD=`tput bold`




### Shark Colors###
S0="${reset}${BLACK}"
S1="${reset}${RED}"
S2="${reset}${GREEN}"
S3="${reset}${YELLOW}"
S4="${reset}${RED}"
S5="${reset}${PURPLE}"
S6="${reset}${CYAN}"
S7="${reset}${YELLOW}"
S10="${BOLD}${GREEN}"
S8="${BOLD}${BLUE}"
S9="${BOLD}${GREEN}"
S11="${BOLD}${PURPLE}"






### Halloween Colors###
H0="${reset}${BLACK}"
H1="${reset}${RED}"
H2="${reset}${GREEN}"
H3="${reset}${YELLOW}"
H4="${reset}${RED}"
H5="${reset}${PURPLE}"
H6="${reset}${CYAN}"
H7="${reset}${YELLOW}"
H10="${BOLD}${GREEN}"
H8="${BOLD}${PURPLE}"
H9="${BOLD}${GREEN}"
H11="${BOLD}${BLUE}"





### Arch Colors ###
A0="${reset}${BLACK}"
A1="${reset}${RED}"
A2="${reset}${GREEN}"
A3="${reset}${YELLOW}"
A4="${reset}${RED}"
A5="${reset}${PURPLE}"
A6="${reset}${CYAN}"
A7="${reset}${YELLOW}"
A10="${BOLD}${GREEN}"
A8="${BOLD}${CYAN}"
A9="${BOLD}${GREEN}"
A11="${BOLD}${BLUE}"








### Shark2 Theme ###
R0="${reset}${BLACK}"
R1="${reset}${RED}"
R2="${reset}${GREEN}"
R3="${reset}${YELLOW}"
R4="${reset}${RED}"
R5="${reset}${PURPLE}"
R6="${reset}${CYAN}"
R7="${reset}${YELLOW}"
R10="${BOLD}${GREEN}"
A8="${BOLD}${CYAN}"
R9="${BOLD}${GREEN}"
C11="${BOLD}${BLUE}"




### System Information ###


HOST=` cat /proc/sys/kernel/hostname`
DISTRO=`lsb_release -ds | sed 's/^.//' | sed 's/.$//'`
USER="$USER@$HOST On Home"
ENV=`wmctrl -m | grep "Name:" | awk '{print $2}'`
KERNEL=`uname -r`
PKG=`pacman -Q | wc -l`
SHELL=`echo $SHELL`
UPTIME=`uptime -p | sed 's/up //'`
TOTAL_RAM=`echo $(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / (1024 * 1024)))`
RAM="$(free | grep Mem | awk '{print $3 / 1024}')"
L_MEM=${RAM%.*}




### If You Want Change Theme , Just Comment Theme, And Uncomment Your Favorite Theme! ###
### Shark Theme (Defualt) ###

                                                                 
                                                                 
echo -e "${S8}                            .::--======++++===-.                                                                            "
echo -e "${S8}                       .:-==++++++++++++====+==+:                                                                           "
echo -e "${S8}                   .-=+++++++++++++++===+*%@@@*-=.                                   ${S11}$USER                            "
echo -e "${S8}                .-=++++++++++++++++==+@%@@@@@@@%-:                                   ${S9}---------------------             "
echo -e "${S8}              :=++++++++++++++++===*%@@@@@@@@@@@%:                                   ${S11}  ${S4}» ${S7}$DISTRO           "
echo -e "${S8}           :=++++++++++++++++==+%@@@@@@@@@@@@@@@-                                    ${S11}漣 ${S4}» ${S7}$KERNEL           "
echo -e "${S8}          :=+======--===++++==+%@@@@@@@@@@@@@@@@@:                                   ${S11}  ${S4}» ${S7}$PKG              "
echo -e "${S8}        .=++========-----=+-+%@@@@@@@@@@@@@@@@@@%-==-:                               ${S11}  ${S4}» ${S7}$UPTIME           "  
echo -e "${S8}       -++=-=++-=--:=*+=-:-*@@@@@@@@@@@@@@@@@@@@@:=+=-                               ${S11}  ${S4}» ${S7}$ENV              "
echo -e "${S8}      -+===+==+.- =.:@@%=:%@@@@@@@@@@@@@@@@@@@@@+:+@%-                               ${S11}  ${S4}» ${S7}$SHELL            "
echo -e "${S8}      =+.=.++====--:=**+-+@@@@@@@@@@@@@@@@@@@@@@-:=+-                                ${S11}  ${S4}» ${S7}$L_MEM MiB / $TOTAL_RAM MiB"
echo -e "${S8}      :+ =::+++====+==-=*@@@@@@@@@@@@@@@@@@@@@@+:=-:                                                                          "
echo -e "${S8}      .--:=:-++++++=--*@@@@@@@@@@@@@@@@@@@@@@@@=                                                                              "
echo -e "${S8}      -::--+==+++==++++**%%%@@@@@@@@@@@@@@@@@@@+.                                                                             "
echo -e "${S8}      :--===++++==%@@@**+++****@@@@@@%%%%%%%%*=.                                                                              "
echo -e "${S8}     :---=++++==@@@@@%%@******************+***                                                                                "
echo -e "${S8}     :---=++++-%@@@@@@@@@%@@@**************@+.                                                                                "
echo -e "${S8}     =+==++++-*@@@@@@@@@@@@@@%%%%%%@@@%%%%%@-                                                                                 "
echo -e "${S8}     -+++++++-%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@=                                                                                 "
echo -e "${S8}     -+++++++-@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*:.                                                                               "
echo -e "${S8}     -+++++++-%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%-=:                                                                              "
echo -e "${S8}     -+++++++-%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@= ==.                                                                            "
echo -e "${S8}     -+===+++-*@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*  :=:                                                                           "
echo -e "${S8}    -++=-=++=+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    --                                                                           "
echo -e "${S8}    -+++=-+++-@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@     :=:                                                                         "
echo -e "${S8}   -+=+-=+=+-*@%@@@@@@@@@@@@@@@@@@@@@@@@@%@*      .=:                                                                         "
echo -e "${S8}   =+++-+++++-%@@@@@@@@@@@@@@@@@@@@@@@@@@@%.        -:                                                                        "
echo -e "${S8}     .::..:::::..==========================-           .                                                                      "
                                                                 









### Halloween Theme ###

#cat << EOF
#${H8}                            ;::;;::;,                                       ${H11}$USER
#${H8}                            ;::;;::;;,                                      ${H9}--------------------- 
#${H8}                           ;;:::;;::;;,                                     ${H11}  ${H4}» ${H7}$DISTRO
#${H8}           .vnmmnv%vnmnv%,.;;;:::;;::;;,  .,vnmnv%vnmnv,                    ${H11}漣 ${H4}» ${H7}$KERNEL
#${H8}        vnmmmnv%vnmmmnv%vnmmnv%;;;;;;;%nmmmnv%vnmmnv%vnmmnv                 ${H11}  ${H4}» ${H7}$PKG
#${H8}      vnmmnv%vnmmmmmnv%vnmmmmmnv%;:;%nmmmmmmnv%vnmmmnv%vnmmmnv              ${H11}  ${H4}» ${H7}$UPTIME 
#${H8}     vnmmnv%vnmmmmmnv%vnmmmmmmmmnv%vnmmmmmmmmnv%vnmmmnv%vnmmmnv             ${H11}  ${H4}» ${H7}$ENV
#${H8}    vnmmnv%vnmmmmmnv%vnmmmmmmmmnv%vnmmmmmmmmmmnv%vnmmmnv%vnmmmnv            ${H11}  ${H4}» ${H7}$SHELL
#${H8}   vnmmnv%vnmmmmmnv%vnmm;mmmmmmnv%vnmmmmmmmm;mmnv%vnmmmnv%vnmmmnv,          ${H11}  ${H4}» ${H7}$L_MEM MiB / $TOTAL_RAM MiB
#${H8}  vnmmnv%vnmmmmmnv%vnmm;' mmmmmnv%vnmmmmmmm;' mmnv%vnmmmnv%vnmmmnv
#${H8}  vnmmnv%vnmmmmmnv%vn;;    mmmmnv%vnmmmmmm;;    nv%vnmmmmnv%vnmmmnv
#${H8} vnmmnv%vnmmmmmmnv%v;;      mmmnv%vnmmmmm;;      v%vnmmmmmnv%vnmmmnv
#${H8} vnmmnv%vnmmmmmmnv%vnmmmmmmmmm;;       mmmmmmmmmnv%vnmmmmmmnv%vnmmmnv
#${H8} vnmmnv%vnmmmmmmnv%vnmmmmmmmmmm;;     mmmmmmmmmmnv%vnmmmmmmnv%vnmmmnv
#${H8} vnmmnv%vnmmmmm nv%vnmmmmmmmmmmnv;, mmmmmmmmmmmmnv%vn;mmmmmnv%vnmmmnv
#${H8} vnmmnv%vnmmmmm  nv%vnmmmmmmmmmnv%;nmmmmmmmmmmmnv%vn; mmmmmnv%vnmmmnv
#${H8} vnmmnv%vnmmmm,  v%vnmmmmmmmmmmnv%vnmmmmmmmmmmnv%v;  mmmmnv%vnnmmnv
#${H8}  vnmmnv%vnmmmm;   %vnmmmmmmmmmnv%vnmmmmmmmmmnv%;   mmmnv%vnmmmmnv
#${H8}   vnmmnv%vnmmmm   nmmm              mmmm    mmmnv%vnmmmmnv
#${H8}   vnmmnv%vnmmmmm;;,.         mmnv%v;,            mmmmnv%vnmmmmnv
#${H8}    vnmmnv%vnmmmmmmnv%vnmmmmmmmmnv%vnmmmmmmnv%vnmmmmmnv%vnmmmmnv
#${H8}      vnmvn%vnmmmmmmnv%vnmmmmmmmnv%vnmmmmmnv%vnmmmmmnv%vnmmmnv
#${H8}          vn%vnmmmmmmn%:%vnmnmmmmnv%vnmmmnv%:%vnmmnv%vnmnv
#EOF







### Arch Theme ###

#cat << EOF
#${A8}           .
#${A8}          / \         ${A11}$USER
#${A8}         /   \        ${A9}---------------------     
#${A8}        /^.   \       ${A11}  ${A4}» ${A7}$DISTRO
#${A8}       /  .-.  \      ${A11}漣 ${A4}» ${A7}$KERNEL
#${A8}      /  (   ) _\     ${A11}  ${A4}» ${A7}$PKG
#${A8}     / _.~   ~._^\    ${A11}  ${A4}» ${A7}$UPTIME
#${A8}    /.^         ^.\   ${A11}  ${A4}» ${A7}$ENV
#${A8}                      ${A11}  ${A4}» ${A7}$SHELL
#${A8}                      ${A11}  ${A4}» ${A7}$L_MEM MiB / $TOTAL_RAM MiB
#EOF









### Shark 2 Theme , Not Complete , DON'T USE IT ###


#ASCII=`cat shark.txt`

#echo -e "          $ASCII                                                                                           "
#echo -e "                                                                                 ${C11}$USER               "
#echo -e "                                                                                 ${R9}---------------------"   
#echo -e "                                                                                 ${C11}  ${R4}» ${R7}$DISTRO"
#echo -e "                                                                                 ${C11}漣 ${R4}» ${R7}$KERNEL"
#echo -e "                                                                                 ${C11}  ${R4}» ${R7}$PKG"
#echo -e "                                                                                 ${C11}  ${R4}» ${R7}$UPTIME"
#echo -e "                                                                                 ${C11}  ${R4}» ${R7}$ENV"
#echo -e "                                                                                 ${C11}  ${R4}» ${R7}$SHELL"
#echo -e "                                                                                 ${C11}  ${R4}» ${R7}$L_MEM MiB / $TOTAL_RAM MiB"

